services:
  serversockettcp:
    image: serversockettcpjoaopaulo
    container_name: serversockettcpjoaopaulo
    ports:
      - '1216:1216'
    restart: unless-stopped 
  
  serversocketudp:
    image: serversocketudpjoaopaulo
    container_name: serversocketudpjoaopaulo
    ports:
      - '4443:1216/udp'
    restart: unless-stopped
